[build]
  publish = "."

[[headers]]
  for = "/db.json.gz"
  [headers.values]
    Content-Type  = "application/octet-stream"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/db-version.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "DENY"
    X-Content-Type-Options = "nosniff"
